"""Add Gemini API Key support

Revision ID: b5b06d12b93d
Revises: 
Create Date: 2026-06-10 17:44:08.591439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b06d12b93d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('kanban_order', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_pattern', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
    
    # SQLite doesn't support dropping columns easily, so we might skip this for safety
    # but since it's an autogenerated migration, let's try to keep it simple.
    # op.drop_column('users', 'ollama_model')
    # op.drop_column('users', 'ollama_base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_api_key')
    op.drop_column('tasks', 'recurrence_pattern')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'kanban_order')
    # ### end Alembic commands ###
